<h1> 1 - Slicing Arrays</h1>

In [88]:
import numpy as np

In [89]:
my_vector = np.array ([-17, -4, 0, 2, 21, 37, 105])

In [90]:
my_vector

array([-17,  -4,   0,   2,  21,  37, 105])

In [91]:
my_vector[0] 

-17

In [92]:
my_vector[0] = -102

In [93]:
my_vector

array([-102,   -4,    0,    2,   21,   37,  105])

In [94]:
my_vector[-3] # drittes Element von Hinten


21

In [95]:
my_vector[305] # Out of Bound - Error

IndexError: index 305 is out of bounds for axis 0 with size 7

Hier kann man sehen:
* `axis` bedeutet bei mehr-dim Array die Dimension

In [96]:
305 % 7 # hier einfach 3 modulo Größe des Vektors

4

In [97]:
my_vector[305 % 7]

21

In [98]:
my_vector.size

7

In [99]:
my_vector[305 % my_vector.size]

21

### Two Dimensional Arrays

In [100]:
my_array= np.arange(35)
my_array.shape = (7,5) # den Array Reshapen zu 7x7 Matrix
my_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [101]:
my_array[2]

array([10, 11, 12, 13, 14])

In [102]:
my_array[10]

IndexError: index 10 is out of bounds for axis 0 with size 7

In [103]:
my_array[4, 20]

IndexError: index 20 is out of bounds for axis 1 with size 5

In [104]:
my_array[-2]

array([25, 26, 27, 28, 29])

In [105]:
my_array[5,2] # in normalen Sprachen eigenlich [5][2] in Python funktioniert beides (siehe unten)

27

In [106]:
row = 5
column = 2
my_array[row, column]

27

In [107]:
my_array[5][2]

27

### Three Dimensional Arrays

In [108]:
my_3D_array = np.arange(70)
my_3D_array.shape = (2, 7, 5)
my_3D_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [109]:
my_3D_array[1]

array([[35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69]])

In [110]:
my_3D_array[1,3]

array([50, 51, 52, 53, 54])

In [111]:
my_3D_array[1,3,2] =1111

In [112]:
my_3D_array

array([[[   0,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9],
        [  10,   11,   12,   13,   14],
        [  15,   16,   17,   18,   19],
        [  20,   21,   22,   23,   24],
        [  25,   26,   27,   28,   29],
        [  30,   31,   32,   33,   34]],

       [[  35,   36,   37,   38,   39],
        [  40,   41,   42,   43,   44],
        [  45,   46,   47,   48,   49],
        [  50,   51, 1111,   53,   54],
        [  55,   56,   57,   58,   59],
        [  60,   61,   62,   63,   64],
        [  65,   66,   67,   68,   69]]])

<h1> 2 - Boolean Mask Arrays</h1>

In [113]:
import numpy as np

In [114]:
my_vector = np.array([-17, -4, 0, 2, 21, 37, 105])
my_vector

array([-17,  -4,   0,   2,  21,  37, 105])

In [115]:
zero_mod_7_mask = 0 == (my_vector % 7) # also wird True/False eingetragen wenn Modulo 0 liefert
zero_mod_7_mask

array([False, False,  True, False,  True, False,  True])

In [116]:
sub_array = my_vector[zero_mod_7_mask] # liefert nur Elemente die True hatten
sub_array

array([  0,  21, 105])

In [117]:
my_vector[True]

array([[-17,  -4,   0,   2,  21,  37, 105]])

In [118]:
my_vector[False]

array([], shape=(0, 7), dtype=int64)

In [119]:
my_vector[[True, False, True, False, True, False, False]] # hier werden Elemente der Arrays vergliechen und nur die True liefert werden ausgegeben (einbisschen wie && und || in JS)

array([-17,   0,  21])

In [120]:
sub_array[sub_array>0] # hier wird 0 rausgenommen

array([ 21, 105])

In [121]:
mod_test = 0 == (my_vector % 7)
mod_test

array([False, False,  True, False,  True, False,  True])

In [122]:
positive_test = my_vector > 0 # jedes Element wird auf > 0 verglichen, wenn True wird ausgegeben
positive_test

array([False, False, False,  True,  True,  True,  True])

In [123]:
combined_mask = np.logical_and(mod_test, positive_test) # logisches und für Elementen mit True für mod_test und positive_test
combined_mask

array([False, False, False, False,  True, False,  True])

In [124]:
my_vector[combined_mask]

array([ 21, 105])

In [125]:
Also:  
man kann die Indexes oder die logischen Methoden von NumPy verweden. logischen Methoden sind besser, wenn die Arrays zu groß sind

SyntaxError: invalid syntax (<ipython-input-125-c2309856d499>, line 1)

<h1>3 - Broadcasting</h1>

Broadcasting = beschreibt wie NumPy Operationen ausführen, wenn Array nicht gleiche Größe haben

In [126]:
import numpy as np

* Broadcast beschreibt wie NumPy Operationen an Array mit verschiedenen Dimensionen ausführt.
    * Arrays müssen kompatibel sein:
        1. die Größen (`size`-Attribute von NumPy-Array) sind gleich
        2. mindestens eine Größe ist 0
* kleinere Array werden an größere Array angepasst

In [127]:
my_3D_array = np.arange(70)
my_3D_array.shape = (2,7,5)
my_3D_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [128]:
# shape
my_3D_array.shape # .shape - Attribute anzeigen

(2, 7, 5)

In [129]:
# number of dimensions
my_3D_array.ndim # .dim - Dimension anzeigen

3

In [130]:
# size; number of elements
my_3D_array.size # .size - Anzahl der Elemente in Array insgesamt

70

In [131]:
my_3D_array[0].size

35

In [132]:
# data type for each element
my_3D_array.dtype # .dtype = Typ der Array bzw. der Elemente anzeigen

dtype('int64')

In [133]:
5 * my_3D_array - 2 # jedes Element * 5 dann - 2 <- hier greift NumPy-Broadcasting-Regel ein => Broadcasting-Rules behandeln Skalare als Array aus einem Element (wird an größten Array angepasst)

array([[[ -2,   3,   8,  13,  18],
        [ 23,  28,  33,  38,  43],
        [ 48,  53,  58,  63,  68],
        [ 73,  78,  83,  88,  93],
        [ 98, 103, 108, 113, 118],
        [123, 128, 133, 138, 143],
        [148, 153, 158, 163, 168]],

       [[173, 178, 183, 188, 193],
        [198, 203, 208, 213, 218],
        [223, 228, 233, 238, 243],
        [248, 253, 258, 263, 268],
        [273, 278, 283, 288, 293],
        [298, 303, 308, 313, 318],
        [323, 328, 333, 338, 343]]])

In [134]:
left_mat = np.arange(6).reshape((2,3)) 
right_mat = np.arange(15).reshape((3,5))

In [135]:
left_mat

array([[0, 1, 2],
       [3, 4, 5]])

In [136]:
right_mat

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [137]:
np.inner(left_mat, right_mat) # da die Matrizen unpassend für Kreuz-Produkt sind

ValueError: shapes (2,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [138]:
np.dot(left_mat, right_mat) # hier ist Ok da Matrizen passend für Punkt-Produkt sind

array([[ 25,  28,  31,  34,  37],
       [ 70,  82,  94, 106, 118]])

### Operations along axes

In [139]:
my_3D_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [140]:
# shape
my_3D_array.shape

(2, 7, 5)

In [141]:
my_3D_array.sum()

2415

In [142]:
(69 * 70)/2 # ist die Gauß-Formel um das gleiche zu erhalten

2415.0

In [143]:
my_3D_array.sum(axis=0) # also my_3D_array[0][0][0] + my_3D_array[1][0][0] + ;  my_3D_array[0][1][0] + my_3D_array[1][1][0]; usw. Also gie gleichen Element aus Matrix 0 und 1

array([[ 35,  37,  39,  41,  43],
       [ 45,  47,  49,  51,  53],
       [ 55,  57,  59,  61,  63],
       [ 65,  67,  69,  71,  73],
       [ 75,  77,  79,  81,  83],
       [ 85,  87,  89,  91,  93],
       [ 95,  97,  99, 101, 103]])

In [144]:
my_3D_array.sum(axis=1) # also my_3D_array[0][1][0] + my_3D_array[0][1][0] + ... my_3D_array[1][0][0] + my_3D_array[0][1][1] + ...; 

array([[105, 112, 119, 126, 133],
       [350, 357, 364, 371, 378]])

In [145]:
my_3D_array.sum(axis=2) # also my_3D_array[0][0][1] + my_3D_array[0][0][2] + ...; my_3D_array[0][1][0] + my_3D_array[0][1][1] + ...; usw

array([[ 10,  35,  60,  85, 110, 135, 160],
       [185, 210, 235, 260, 285, 310, 335]])

<h2>Broadcasting Rules</h2>

In [146]:
my_2D_array = np.ones(35, dtype='int_').reshape((7,5)) * 3
my_2D_array

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [147]:
my_random_2D_array = np.random.random((7,5))
my_random_2D_array

array([[0.4212, 0.4761, 0.5519, 0.4175, 0.1035],
       [0.7987, 0.3284, 0.1509, 0.3218, 0.546 ],
       [0.3235, 0.6645, 0.7597, 0.6512, 0.7072],
       [0.6978, 0.3834, 0.2228, 0.2394, 0.7743],
       [0.7252, 0.7977, 0.6373, 0.8474, 0.1633],
       [0.7574, 0.7876, 0.847 , 0.3888, 0.568 ],
       [0.6644, 0.2616, 0.0358, 0.779 , 0.7136]])

In [148]:
np.set_printoptions(precision=4) # Ausgabe für Elemente auf 4 Nachkommastellen einstellen
my_3D_array * my_random_2D_array # alles OK => intern werden Broadcasting Regeln gecheckt, da kein Error => beide Arrays sind Kompatibel zu einander für Multiplikaitoin via Broadcasting

array([[[ 0.    ,  0.4761,  1.1037,  1.2525,  0.4141],
        [ 3.9933,  1.9702,  1.056 ,  2.5743,  4.9138],
        [ 3.2347,  7.3096,  9.1162,  8.4657,  9.9013],
        [10.4671,  6.1344,  3.787 ,  4.3088, 14.7113],
        [14.5043, 16.7512, 14.0217, 19.4906,  3.9181],
        [18.9361, 20.4764, 22.8692, 10.8873, 16.4732],
        [19.9319,  8.1103,  1.1442, 25.7084, 24.264 ]],

       [[14.7432, 17.1392, 20.4194, 15.8644,  4.0372],
        [31.9467, 13.4632,  6.336 , 13.8367, 24.0229],
        [14.5561, 30.5672, 35.7052, 31.2581, 34.6547],
        [34.8902, 19.5535, 11.5838, 12.687 , 41.8112],
        [39.8868, 44.6699, 36.3289, 49.1502,  9.6321],
        [45.4466, 48.0408, 52.5144, 24.4964, 36.3547],
        [43.1857, 17.2671,  2.3957, 52.9748, 49.2417]]])

In [149]:
my_vector = np.arange(5) * 7 # 1-Dim Array 
my_vector[0] = -1
my_vector

array([-1,  7, 14, 21, 28])

In [150]:
my_3D_array / my_vector

array([[[ -0.    ,   0.1429,   0.1429,   0.1429,   0.1429],
        [ -5.    ,   0.8571,   0.5   ,   0.381 ,   0.3214],
        [-10.    ,   1.5714,   0.8571,   0.619 ,   0.5   ],
        [-15.    ,   2.2857,   1.2143,   0.8571,   0.6786],
        [-20.    ,   3.    ,   1.5714,   1.0952,   0.8571],
        [-25.    ,   3.7143,   1.9286,   1.3333,   1.0357],
        [-30.    ,   4.4286,   2.2857,   1.5714,   1.2143]],

       [[-35.    ,   5.1429,   2.6429,   1.8095,   1.3929],
        [-40.    ,   5.8571,   3.    ,   2.0476,   1.5714],
        [-45.    ,   6.5714,   3.3571,   2.2857,   1.75  ],
        [-50.    ,   7.2857,   3.7143,   2.5238,   1.9286],
        [-55.    ,   8.    ,   4.0714,   2.7619,   2.1071],
        [-60.    ,   8.7143,   4.4286,   3.    ,   2.2857],
        [-65.    ,   9.4286,   4.7857,   3.2381,   2.4643]]])

In [151]:
my_3D_array % my_vector

array([[[ 0,  1,  2,  3,  4],
        [ 0,  6,  7,  8,  9],
        [ 0,  4, 12, 13, 14],
        [ 0,  2,  3, 18, 19],
        [ 0,  0,  8,  2, 24],
        [ 0,  5, 13,  7,  1],
        [ 0,  3,  4, 12,  6]],

       [[ 0,  1,  9, 17, 11],
        [ 0,  6,  0,  1, 16],
        [ 0,  4,  5,  6, 21],
        [ 0,  2, 10, 11, 26],
        [ 0,  0,  1, 16,  3],
        [ 0,  5,  6,  0,  8],
        [ 0,  3, 11,  5, 13]]])

# 4 - Structured and record arrays

### Creating Structured Arrays

In [152]:
import numpy as np

In [153]:
person_data_def = [('name','S6'),('height','f8'),('weight','f8'), ('age', 'i8')] # hier wird eigentlich Typ definiert (man muss in Doku schauen, was S6, f8, i8 bedeuten (wahrscheinlich Datentypen)) ! wahrscheinlich wie man eigene Typen für NumPy-Arrays definiert
person_data_def

[('name', 'S6'), ('height', 'f8'), ('weight', 'f8'), ('age', 'i8')]

In [154]:
people_array = np.zeros((4,), dtype=person_data_def) # array aus 4 Elementen, jedes Element ist vom Typ person_data_def 
people_array # der Inhalte der Elemente wird auf NULL gesetzt

array([(b'', 0., 0., 0), (b'', 0., 0., 0), (b'', 0., 0., 0),
       (b'', 0., 0., 0)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [155]:
people_array2 = np.zeros((2,), dtype=person_data_def)
people_array2

array([(b'', 0., 0., 0), (b'', 0., 0., 0)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [156]:
people_array[3] = ('Delta', 73, 205, 34) # (name=Delta, height=73, weight=205, age=34)
people_array[0] = ('Alpha', 65, 112, 23)
people_array

array([(b'Alpha', 65., 112., 23), (b'',  0.,   0.,  0),
       (b'',  0.,   0.,  0), (b'Delta', 73., 205., 34)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [157]:
people_array[0:]

array([(b'Alpha', 65., 112., 23), (b'',  0.,   0.,  0),
       (b'',  0.,   0.,  0), (b'Delta', 73., 205., 34)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [158]:
ages = people_array['age'] # nur `age` aus den einzelnen Elementen holen
ages

array([23,  0,  0, 34])

In [159]:
type(ages)

numpy.ndarray

In [160]:
make_youthful = ages / 2 # Broadcastin-Regeln werden angewednet da (siehe oben ist NumPy-Array)
make_youthful

array([11.5,  0. ,  0. , 17. ])

In [161]:
people_array

array([(b'Alpha', 65., 112., 23), (b'',  0.,   0.,  0),
       (b'',  0.,   0.,  0), (b'Delta', 73., 205., 34)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [162]:
ages

array([23,  0,  0, 34])

### Multi-dimensional Structured Arrays

In [163]:
people_big_array = np.zeros((4,3,2), dtype=person_data_def)
people_big_array

array([[[(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)]],

       [[(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)]],

       [[(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)]],

       [[(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)]]],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [164]:
type(people_big_array)

numpy.ndarray

In [165]:
people_big_array[3,2,1] = ('Echo', 68, 155, 46)
people_big_array

array([[[(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)],
        [(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)],
        [(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)]],

       [[(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)],
        [(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)],
        [(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)]],

       [[(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)],
        [(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)],
        [(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)]],

       [[(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)],
        [(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)],
        [(b'',  0.,   0.,  0), (b'Echo', 68., 155., 46)]]],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [166]:
people_big_array['height']

array([[[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0., 68.]]])

In [167]:
people_big_array[['height', 'weight']]  # nur height and weight rausholen

array([[[( 0.,   0.), ( 0.,   0.)],
        [( 0.,   0.), ( 0.,   0.)],
        [( 0.,   0.), ( 0.,   0.)]],

       [[( 0.,   0.), ( 0.,   0.)],
        [( 0.,   0.), ( 0.,   0.)],
        [( 0.,   0.), ( 0.,   0.)]],

       [[( 0.,   0.), ( 0.,   0.)],
        [( 0.,   0.), ( 0.,   0.)],
        [( 0.,   0.), ( 0.,   0.)]],

       [[( 0.,   0.), ( 0.,   0.)],
        [( 0.,   0.), ( 0.,   0.)],
        [( 0.,   0.), (68., 155.)]]],
      dtype={'names':['height','weight'], 'formats':['<f8','<f8'], 'offsets':[6,14], 'itemsize':30})

<h2>Creating Record Arrays</h2>
* ähnlich wie Structured Array + Wrapped mittels Subklass "NumPy.record"
* man kann dann über Attribute-Namen auf den Array zugreifen
* eigenlich record erweiterd structured

In [168]:
test_record: np.recarray
test_structed: np.ndarray

In [169]:
person_record_array = np.rec.array([('Delta', 73, 205, 34),('Alpha', 65, 112, 23)],dtype=person_data_def)
person_record_array

rec.array([(b'Delta', 73., 205., 34), (b'Alpha', 65., 112., 23)],
          dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [170]:
person_record_array[0].age # man kann dan auf 

34

In [171]:
type(person_record_array)

numpy.recarray