# 1 - Create Arrays from Python Structure

<h2>Create NumPy arrays using Python's "array like" data types</h2>


In [1]:
import numpy as np # Alias np für Namespace numpy

In [2]:
print (np.__version__) # Version von Numpy anzeigen

1.18.4


In [3]:
my_list = [-17, 0, 4, 5, 9] # Python Array anlegen
my_array_from_list = np.array(my_list) # Python-Array zum NumPy-Array umwandeln
my_array_from_list

array([-17,   0,   4,   5,   9])

In [4]:
my_array_from_list * 10 # in NumPy kann man Operationen "Element für Element" ausführen

array([-170,    0,   40,   50,   90])

In [5]:
my_tuple = (14, -3.54, 5+7j) # Array aus Python-Tupel
np.array(my_tuple) # es werden alle Elemente auf den größt möglichen Typ umgewandelt. Alle Elemente in NumPy-Array müssen gleichen Typen haben

array([14.  +0.j, -3.54+0.j,  5.  +7.j])

### Difference between python and numpy data structures

In [6]:
my_tuple * 6 # Python-Tupel => Array wird 6 Mal angelegt

(14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j))

In [7]:
np.array(my_tuple) * 6 # NumPy-Array => Operation Element für Element

array([ 84.   +0.j, -21.24 +0.j,  30.  +42.j])

# 2 - Intrinsic creation using NumPy methods

<h2>Intrinsic NumPy array creation using NumPy's methods</h2>

In [8]:
import numpy as np

In [9]:
arange(7) # versucht Funtion aus Python Std-Bibliothek auszuführen bzw. versucht Funktion aus "python" Namespace auszuführen

NameError: name 'arange' is not defined

In [10]:
np.arange(7) # per Default start=0, step=1; stop=7

array([0, 1, 2, 3, 4, 5, 6])

In [11]:
np.arange(10, 23) # mit start=10, stop=23

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])

In [12]:
np.arange(10, 23) - 10 # 10 von jedem Element abziehen

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [13]:
np.arange(10, 23) - 10 + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [14]:
len (np.arange(10, 23)) # Länge bestimmen Version 1

13

In [15]:
my_range_array = np.arange(10, 23)
my_range_array.size # Länge besitmmen Version 2

13

In [16]:
np.arange(10, 23).size # Länge bestimmen eigentlich auch Version 2

13

In [17]:
np.arange(10, 23, 5) # mit start=10, stop=23, step=5 (start ist inklusive, stop is exklusive)

array([10, 15, 20])

In [18]:
np.arange(10, 25, 5) #start ist inklusive, stop is exklusive

array([10, 15, 20])

In [19]:
np.arange(10, 26, 5) #start ist inklusive, stop is exklusive

array([10, 15, 20, 25])

In [20]:
np.arange(26, step=5) # mit start=0 (default), stop=23, step=5

# hier muss man step=5 mitangeben, sonst wird start, stop angnommen

array([ 0,  5, 10, 15, 20, 25])

In [21]:
np.arange(0, 26, step=5)

array([ 0,  5, 10, 15, 20, 25])

In [22]:
np.arange(0, 26, 5)

array([ 0,  5, 10, 15, 20, 25])

# 2 - linspace zeros ones data types

In [23]:
import numpy as np

* `linsapce()` - Integer-Array, die gleichen Abstand haben
* `zeros()` - Integer-Array mit Nullen
* `ones()` - Integer-Array mit Einsen

In [24]:
np.linspace(5, 15, 9) # (start, stop, ...) - sind verpflichtend, (start, stop, num(anazahl)); start und stop sind inklusive

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  , 11.25, 12.5 , 13.75, 15.  ])

In [25]:
my_linspace = np.linspace(5, 15, 9, retstep=True) # mit restStep=True wird auch StepSize in NumPy-Array abgelegt dabe sieht das Array dan so aus my_linspace[[5, ... 15][stepSize]]

In [26]:
my_linspace[0]

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  , 11.25, 12.5 , 13.75, 15.  ])

In [27]:
my_linspace[1]

1.25

In [28]:
np.linspace(5, 15, 9, retstep=True)[1]

1.25

<h2>zeros()</h2>

In [29]:
np.zeros(5) # wird mit Floats gefüllt

array([0., 0., 0., 0., 0.])

<h2>ones()</h2>

In [30]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [31]:
np.zeros((5,4,3)) # 3dim-Array mit Matrizen 4-Rows x 3-Columns

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

<h2>NumPy data types()</h2>

In [32]:
np.zeros(11, dtype='int64') # man kann mit dem Param dtype Typ zum Anlegen bestimmten (default ist Float)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [33]:
np.zeros(11)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
class Test:
    stat_test1: int = 10
    
    def __init__(self, num: int = 0):
        self.stat_test1 = self.stat_test1 + 1
        
        if num == 0:
            self.__test1__ = self.stat_test1
        else:
            self.__test1__ = num 

In [35]:
np.zeros(5, dtype=int)
test1 = Test()
test2 = Test()
print(test2.stat_test1)

11
