# 1 - Universal Functions

###Universal Functions

for more information: http://docs.scipy.org/doc/numpy/reference/ufuncs.html

In [1]:
import numpy as np

In [2]:
# truncated binomial: returns (x+1)**3 - (x)**3
def truncated_binomial(x):
    return (x+1)**3 - (x)**3

In [3]:
np.testing.assert_equal (truncated_binomial(4), 61)

In [4]:
np.testing.assert_equal (truncated_binomial(4), 65)

AssertionError: 
Items are not equal:
 ACTUAL: 61
 DESIRED: 65

for information about frompyfunc(), see: http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.frompyfunc.html

In [9]:
my_numpy_function = np.frompyfunc(truncated_binomial, 1, 1)
my_numpy_function

<ufunc '? (vectorized)'>

In [10]:
test_array = np.arange(10)
test_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
my_numpy_function(test_array)

array([1, 7, 19, 37, 61, 91, 127, 169, 217, 271], dtype=object)

In [15]:
big_test_array = np.outer(test_array, test_array)
big_test_array

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 0,  8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81]])

In [14]:
my_numpy_function(big_test_array)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 7, 19, 37, 61, 91, 127, 169, 217, 271],
       [1, 19, 61, 127, 217, 331, 469, 631, 817, 1027],
       [1, 37, 127, 271, 469, 721, 1027, 1387, 1801, 2269],
       [1, 61, 217, 469, 817, 1261, 1801, 2437, 3169, 3997],
       [1, 91, 331, 721, 1261, 1951, 2791, 3781, 4921, 6211],
       [1, 127, 469, 1027, 1801, 2791, 3997, 5419, 7057, 8911],
       [1, 169, 631, 1387, 2437, 3781, 5419, 7351, 9577, 12097],
       [1, 217, 817, 1801, 3169, 4921, 7057, 9577, 12481, 15769],
       [1, 271, 1027, 2269, 3997, 6211, 8911, 12097, 15769, 19927]], dtype=object)

# 2 - Pythagorean Triangles

## Linear Algebra

In [ ]:
import numpy as np

In [ ]:
my_first_matrix = np.matrix([[3, 1, 4], [1, 5, 9], [2, 6, 5]])
my_first_matrix

In [ ]:
http://docs.scipy.org/doc/numpy/reference/generated/numpy.matrix.html

In [ ]:
# transpose
my_first_matrix.T

In [ ]:
# matrix inverse
my_first_inverse = my_first_matrix.I
my_first_inverse

In [ ]:
#should return inverse; floating point values "almost" equal zero
my_first_matrix * my_first_inverse

In [ ]:
# create an identity matrix
np.eye(5)

In [ ]:
### Solve simultaneous linear equations

In [ ]:
right_hand_side = np.matrix([[11],
                             [22],
                             [33]])

In [ ]:
# not efficient; use only for small matrices
solution = my_first_inverse * right_hand_side
solution

In [ ]:
# confirm that solution is correct
my_first_matrix * solution - right_hand_side

In [ ]:
# more efficient for large matrices
from numpy.linalg import solve
solve(my_first_matrix, right_hand_side)

In [ ]:
# Compute the eigenvalues and right eigenvectors
from numpy.linalg import eig
eig(my_first_matrix)

# 3 - Linear Algebra

In [ ]:
import numpy as np

In [ ]:
my_first_matrix = np.matrix([[3, 1, 4], [1, 5, 9], [2, 6, 5]])
my_first_matrix

In [ ]:
http://docs.scipy.org/doc/numpy/reference/generated/numpy.matrix.html

In [ ]:
# transpose
my_first_matrix.T

In [ ]:
# matrix inverse
my_first_inverse = my_first_matrix.I
my_first_inverse

In [ ]:
#should return inverse; floating point values "almost" equal zero
my_first_matrix * my_first_inverse

In [ ]:
# create an identity matrix
np.eye(5)

In [ ]:
right_hand_side = np.matrix([[11],
                             [22],
                             [33]])

In [ ]:
# not efficient; use only for small matrices
solution = my_first_inverse * right_hand_side
solution

In [ ]:
# confirm that solution is correct
my_first_matrix * solution - right_hand_side

In [ ]:
# more efficient for large matrices
from numpy.linalg import solve
solve(my_first_matrix, right_hand_side)

In [ ]:
# Compute the eigenvalues and right eigenvectors
from numpy.linalg import eig
eig(my_first_matrix)

# 4 - Finding pattern

In [ ]:
import numpy as np

## Given this array, find the next number in the sequence

In [ ]:
my_teaser_array = np.array([1, 7, 19, 37, 61, 91, 127, 169, 217, 271, 331])
my_teaser_array

In [ ]:
##### for information about numpy.diff, please see: http://docs.scipy.org/doc/numpy/reference/generated/numpy.diff.html

In [ ]:
np.diff(my_teaser_array)

In [ ]:
np.diff(my_teaser_array, n=2)

In [ ]:
np.diff(my_teaser_array, n=3)

##### Warning: imports should (usually) appear at top of notebook

If SymPy is not included on your computer; open a console and type 'conda sympy'

In [ ]:
from sympy import init_session
init_session() 

In [ ]:
diff(x**3)

In [ ]:
diff(x**3, x, 2)

In [ ]:
diff(x**3, x, 3)

In [ ]:
diff(x**3, x, 4)

In [ ]:
def my_guess(n):
    return (n+1)**3 - n**3

In [ ]:
my_teaser_array = np.array([1, 7, 19, 37, 61, 91, 127, 169, 217, 271, 331])
my_teaser_array

# 5 - Statistics

In [ ]:
## Statistics
- import statistical methods
- find information about statistical methods
- perform rudimentary statistical operations
- plot output from statistical operations

In [ ]:
%matplotlib inline
import scipy as sp
import numpy as np
import matplotlib.pyplot as plt

from scipy.stats import norm

In [ ]:
##### sample data set

In [ ]:
number_of_data_points = 99
random_data_set = sp.randn(number_of_data_points)
type(random_data_set)

In [ ]:
#### descriptive statistics
##### mean

In [ ]:
random_data_set.mean()

In [ ]:
##### median

In [ ]:
sp.median(random_data_set)

In [ ]:
min_max = np.array([random_data_set.min(), random_data_set.max()])
min_max

In [ ]:
##### standard deviation and variance

In [ ]:
spread_measures = np.array([sp.std(random_data_set), sp.var(random_data_set)])
spread_measures

In [ ]:
sp.stats.describe(random_data_set)

In [ ]:
### Probability Distributions
- continuous distributions
    - Normal: norm
    - Chi squared: chi2
    - Student's T: t
    - Uniform: uniform
- discrete distributions
    - Poisson: poisson
    - Binomial: binomial

In [ ]:
#### Normal Distribution
documentation: http://docs.scipy.org/doc/scipy-0.16.0/reference/generated/scipy.stats.norm.html

In [ ]:
iq_mean = 100
iq_std_dev = 15
iq_distribution = norm(loc=iq_mean, scale=iq_std_dev)
for n in np.arange(8):
    print('{:6.2f}'.format(iq_distribution.rvs()))

In [ ]:
##### probability density function (PDF)

For continuous variates, PDF is proportional to the probability of the variate being in a small interval about the input parameter

In [ ]:
iq_pdf = iq_distribution.pdf(110)
print('{:6.2f}'.format(iq_pdf))

In [ ]:
##### cumulative density function (CDF)

For continuous variates, CDF gives the probability that the variate has a value less than or equal to the input parameter

In [ ]:
iq_value = 120
iq_below = iq_distribution.cdf (iq_value)
iq_above = 1 - iq_below
print('Probability that IQ is below{:4d} is {:4.2f}; probability above: {:4.2f}'.format(iq_value, iq_below, iq_above))

In [ ]:
mu, sigma = 100, 15
data_set = mu + sigma * np.random.randn(10000)

# the histogram of the data
n, bins, patches = plt.hist(data_set, 50, normed=1, facecolor='g', alpha=0.75)

plt.xlabel('IQ Score')
plt.ylabel('Probability')
plt.title('Histogram of IQ')
plt.text(60, .025, r'$\mu=100,\ \sigma=15$')
plt.axis([40, 160, 0, 0.03])
plt.grid(True)
plt.show()

# 6 - Brain Teasers

## Brain Teasers
for more brain teasers, please see: http://www.labri.fr/perso/nrougier/teaching/numpy.100/index.html

In [ ]:
# Brain Teasers
for more brain teasers, please see: http://www.labri.fr/perso/nrougier/teaching/numpy.100/index.html

### What version of NumPy are you using?

In [ ]:
# note double underscrore 
print(np.__version__)

### Display array elements in reverse order

In [ ]:
my_array = np.array(np.arange(10))
my_array

In [ ]:
my_array[::-1]

### Triple elements in array

In [ ]:
my_array * 3

In [ ]:
my_array = np.zeros(20)
my_array[0::5] = 4
my_array

### Create a 3x3 matrix whose elements equal 0 through 8

In [ ]:
my_matrix = np.asmatrix(np.array(np.arange(9)).reshape((3,3)))
my_matrix

### Transpose the rows and columns

In [ ]:
my_matrix.T

### Create a 5x5 identity matrix with integer components

In [ ]:
my_matrix = np.asmatrix(np.eye(5, dtype='int'))
my_matrix

### Find the mean of a vector with 30 random elements.  Can you guess the approximate value for the mean?

In [ ]:
my_random_vector = np.random.random(30)
my_random_vector.mean()

#### Repeat, and visually estimate the mean for the sum of the two means

In [ ]:
my_random_vector = np.random.random(30)
my_random_vector.mean()

### Create a 2d array with ones on the border and zeros inside the border

In [ ]:
my_bordered_array = np.ones((5,5))
my_bordered_array[1:-1,1:-1] = 0
my_bordered_array

### Create an 8x8 checker board with alternating zeros and ones

In [ ]:
my_checker_board = np.zeros((8,8),dtype=int)
my_checker_board[1::2,::2] = 1
my_checker_board[::2,1::2] = 1
print(my_checker_board)

In [ ]:
my_alternative_checker_board = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(my_alternative_checker_board)

### Create a sorted vector that contain 'n' random numbers

In [ ]:
vector_size = 12
my_random_vector = np.random.random(vector_size)
my_sorted_random_vector = np.sort(my_random_vector)
print (my_sorted_random_vector)

### Without sorting, replace largest element in random array with the value 1234

In [ ]:
my_random_vector[my_random_vector.argmax()] = 1234
my_random_vector

### Given the following data type and data set; sort according to 'height'

source: http://docs.scipy.org/doc/numpy/reference/generated/numpy.sort.html

In [ ]:
camelot_dtype = [('name', 'S10'), ('height', float), ('age', int)]
camelot_values = [('Arthur', 1.8, 41), ('Lancelot', 1.9, 38), ('Galahad', 1.7, 38)]

### Make an array read-only (immutable)

In [ ]:
my_ordinary_array = np.array(np.arange(12))
my_ordinary_array.flags.writeable = False
my_ordinary_array[5] = 1234

In [ ]:
my_3_3_array = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(my_3_3_array):
    print(index, value)
