# 1- Views and Copies

In [2]:
import numpy as np

In [3]:
mi_casa = np.array([-45, -31, -12, 0, 2, 25, 51, 99])

In [4]:
su_casa = mi_casa

### Same or Different?

In [7]:
#reference equality
mi_casa is su_casa

True

In [8]:
id(mi_casa)

4481339184

In [9]:
id(su_casa)

4481339184

In [10]:
#value inequality
mi_casa == su_casa

array([ True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [11]:
su_casa[4] = 1010

In [12]:
su_casa

array([ -45,  -31,  -12,    0, 1010,   25,   51,   99])

In [13]:
su_casa

array([ -45,  -31,  -12,    0, 1010,   25,   51,   99])

In [14]:
mi_casa

array([ -45,  -31,  -12,    0, 1010,   25,   51,   99])

In [15]:
tree_house = np.array([-45, -31, -12, 0, 2, 25, 51, 99])

In [16]:
tree_house == mi_casa

array([ True,  True,  True,  True, False,  True,  True,  True], dtype=bool)

In [17]:
id(tree_house)

4400009088

In [18]:
id(mi_casa)

4481339184

In [19]:
tree_house[0] = 214

In [20]:
tree_house

array([214, -31, -12,   0,   2,  25,  51,  99])

In [21]:
mi_casa

array([ -45,  -31,  -12,    0, 1010,   25,   51,   99])

In [22]:
tree_house == mi_casa

array([False,  True,  True,  True, False,  True,  True,  True], dtype=bool)

In [23]:
tree_house is mi_casa

False

## View: a shallow copy

In [25]:
farm_house = tree_house.view()
farm_house.shape = (2,4)

In [26]:
tree_house

array([214, -31, -12,   0,   2,  25,  51,  99])

In [27]:
farm_house

array([[214, -31, -12,   0],
       [  2,  25,  51,  99]])

In [28]:
tree_house [3] = -111

In [29]:
farm_house

array([[ 214,  -31,  -12, -111],
       [   2,   25,   51,   99]])

## Deep Copy


In [30]:
dog_house = np.copy(tree_house)
dog_house[0] = -121
dog_house

array([-121,  -31,  -12, -111,    2,   25,   51,   99])

In [31]:
tree_house

array([ 214,  -31,  -12, -111,    2,   25,   51,   99])

# 2 - Arrays attributes

In [ ]:
### Attributes of NumPy Arrays
- Number of dimensions
- shape
- size (number of elements)
- data type for elements
- item size for each element within an array
- type (for the array; not for elements within array)

In [ ]:
import numpy as np

In [ ]:
a = np.arange(24).reshape((2,3,4))
a

In [ ]:
a.ndim

In [ ]:
a.shape

In [ ]:
a.size

In [ ]:
a.dtype

In [ ]:
a.itemsize

In [ ]:
type(a)

# 3 - Add and Remove Elements

## Adding and Removing Elements from NumPy Arrays
- append
- horizontal stacking
- vertical stacking
- insert
- delete

In [ ]:
import numpy as np

In [ ]:
a = np.array(np.arange(24)).reshape(2,3,4)
a

In [ ]:
b=np.append(a, [5,6,7,8])
b

In [ ]:
b.shape

In [ ]:
b.reshape((7,4))

In [ ]:
a

In [ ]:
c = np.array(np.arange(24)).reshape(2,3,4) * 10 + 3
c

In [ ]:
np.append(a,c, axis=0)

In [ ]:
np.append(a,c, axis=0).shape

In [ ]:
np.append(a,c, axis=1)

In [ ]:
np.append(a,c, axis=1).shape

In [ ]:
np.append(a,c, axis=2)

In [ ]:
np.append(a,c, axis=2).shape

In [ ]:
my_hay_stack = np.hstack((a,c))
my_hay_stack

In [ ]:
my_hay_stack[0,0,2] = 999

In [ ]:
my_hay_stack

In [ ]:
a

In [ ]:
c

In [ ]:
after_insert_array = np.insert (c, 1, 444, axis=0)
after_insert_array

In [ ]:
np.insert (c, 1, 444, axis=1)

In [ ]:
np.insert (c, 1, 444, axis=2)

In [ ]:
d = np.empty(c.shape)
np.copyto(d, c)
d

In [ ]:
np.delete(d, 1, axis=0)

In [ ]:
np.delete(d, 1, axis=1)

In [ ]:
np.delete(d, 1, axis=2)

# 4 - Join and Split Arrays

In [ ]:
## Joining and Splitting arrays
- concatenate
- stack
- split

In [ ]:
import numpy as np

In [ ]:
### concatenate
documentation: http://docs.scipy.org/doc/numpy/reference/generated/numpy.concatenate.html

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
a

In [ ]:
together = np.concatenate((a, b), axis=0)
together

In [ ]:
together.shape

In [ ]:
together[1,1] = 555
together

In [ ]:
a

In [ ]:
c = np.array([[1, 2], [3, 4]]) *3 + 5
c

In [ ]:
np.concatenate((a, c), axis=1)

In [ ]:
arrays = np.zeros((5,3,4))
for n in range(5):
    arrays[n] = np.random.randn(3, 4)
    
arrays

In [ ]:
stack0 = np.stack(arrays, axis=0)
stack1 = np.stack(arrays, axis=1)
stack2 = np.stack(arrays, axis=2)

In [ ]:
my_stacks = np.array([stack0.shape, stack1.shape, stack2.shape])
my_stacks

In [ ]:
stack0

In [ ]:
stack1

In [ ]:
stack2

### split
for information, please see: http://docs.scipy.org/doc/numpy/reference/generated/numpy.split.html

In [ ]:
temp = np.arange(5)
np.split(temp,1)

In [ ]:
before_split = stack0
before_split.shape

In [ ]:
s0=np.split (before_split, 5, axis=0)
s0

In [ ]:
type(s0)

In [ ]:
s0[1]

In [ ]:
s0[1].shape

In [ ]:
s2=np.split (before_split, 4, axis=2)
s2

# 5 - Array shape manipulation

In [ ]:
import numpy as np

In [ ]:
### reshape
from: http://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html#numpy.reshape

NOTE: This will be a new view object if possible; otherwise, it will be a copy.

In [ ]:
my_start_array = np.array(np.arange(24))
my_start_array

In [ ]:
my_start_array.shape

In [ ]:
my_3_8_array = my_start_array.reshape((3,8))
my_3_8_array

In [ ]:
my_3_8_array[0,0] = 1234

In [ ]:
my_start_array

In [ ]:
my_ravel_array = my_3_8_array.ravel()

In [ ]:
my_ravel_array

In [ ]:
my_ravel_array.shape

In [ ]:
for n in my_3_8_array.flat:
    print(n)

# 6 - Rearrange array elements

In [ ]:
import numpy as np
my_start_array = np.array(np.arange(24))
my_3_8_array = my_start_array.reshape((3,8))
my_2_3_4_array = my_3_8_array.reshape((2,3,4))

### fliplr "flip left right"
from: http://docs.scipy.org/doc/numpy/reference/generated/numpy.fliplr.html#numpy.fliplr

Flip array in the left/right direction.

In [ ]:
my_3_8_array

In [ ]:
np.fliplr(my_3_8_array)

In [ ]:
my_2_3_4_array

In [ ]:
np.fliplr(my_2_3_4_array)

In [ ]:
np.flipud(my_3_8_array)

In [ ]:
np.flipud(my_2_3_4_array)

In [ ]:
my_start_array

In [ ]:
np.roll(my_start_array, 5)

In [ ]:
np.roll(my_start_array, -5)

In [ ]:
np.roll(my_2_3_4_array, 2)

In [ ]:
np.roll(my_2_3_4_array, -2)

In [ ]:
my_3_8_array

In [ ]:
np.rot90(my_3_8_array)

In [ ]:
np.rot90(my_3_8_array, k=-1)

# 7 - Transpose like operations

- transpose
- swapaxes
- rollaxes

In [ ]:
import numpy as np

In [ ]:
my_start_array = np.array(np.arange(24))
my_3_8_array = my_start_array.reshape((3,8))
my_2_3_4_array = my_3_8_array.reshape((2,3,4))

In [ ]:
### transpose
for more information, please see: http://docs.scipy.org/doc/numpy/reference/generated/numpy.transpose.html

1-Dimension, no change

In [ ]:
my_start_array

##### 2-Dimensions, 
exchange rows and columns (`a[i,j] becomes a[j,i]`)

In [ ]:
my_3_8_array

In [ ]:
np.transpose(my_3_8_array)

##### 3-Dimensions or more,
use 'axes' parameter

In [ ]:
my_2_3_4_array

In [ ]:
np.transpose(my_2_3_4_array, axes=(0,2,1))

In [ ]:
np.transpose(my_2_3_4_array, axes=(2,1,0))

### swapaxes
from: http://docs.scipy.org/doc/numpy/reference/generated/numpy.swapaxes.html#numpy.swapaxes

##### returns
For Numpy >= 1.10, if a is an ndarray, then a view of a is returned; otherwise a new array is created. For earlier Numpy versions a view of a is returned only if the order of the axes is changed, otherwise the input array is returned.

In [ ]:
np.swapaxes(my_2_3_4_array, 1, 0)

In [ ]:
my_2_3_4_array

In [ ]:
np.swapaxes(my_2_3_4_array, 1, 0).shape

In [ ]:
np.swapaxes(my_2_3_4_array, 2, 1)

In [ ]:
np.swapaxes(my_2_3_4_array, 2, 0)

In [ ]:
### rollaxis
from: http://docs.scipy.org/doc/numpy/reference/generated/numpy.rollaxis.html#numpy.rollaxis

Roll the specified axis backwards, until it lies in a given position.

For Numpy >= 1.10 a view of a is always returned. For earlier Numpy versions a view of a is returned only if the order of the axes is changed, otherwise the input array is returned.

In [ ]:
my_2_3_4_array

In [ ]:
np.rollaxis(my_2_3_4_array, 0, 2)

In [ ]:
np.rollaxis(my_2_3_4_array, 0, 2).shape

In [ ]:
##### Summary; from: http://stackoverflow.com/questions/15483156/generalizing-matrix-transpose-in-numpy

- Use np.transpose to permute all the axes at once. (Thanks to @jorgeca for pointing this out.)
- Use np.swapaxes to swap any two axes.
- Use np.rollaxis to "rotate" the axes.